# Generated by Django 5.0.6 on 2024-05-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_pass', '0003_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, choices=[('2A', 'NORMAL'), ('3A', 'HARD'), ('1A', 'EASY')], default='1A', max_length=2, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, choices=[('2A', 'NORMAL'), ('3A', 'HARD'), ('1A', 'EASY')], default='1A', max_length=2, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, choices=[('2A', 'NORMAL'), ('3A', 'HARD'), ('1A', 'EASY')], default='1A', max_length=2, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, choices=[('2A', 'NORMAL'), ('3A', 'HARD'), ('1A', 'EASY')], default='1A', max_length=2, verbose_name='Зима'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('RJ', 'отклонён'), ('NW', 'новый'), ('AC', 'принят'), ('PN', 'в работе')], default='NW', max_length=2),
        ),
    ]
