# Generated by Django 5.0.6 on 2024-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_pass', '0004_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('1A', 'EASY'), ('NO', '-----'), ('3A', 'HARD'), ('2A', 'NORMAL')], default='NO', max_length=2, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('1A', 'EASY'), ('NO', '-----'), ('3A', 'HARD'), ('2A', 'NORMAL')], default='NO', max_length=2, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('1A', 'EASY'), ('NO', '-----'), ('3A', 'HARD'), ('2A', 'NORMAL')], default='NO', max_length=2, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('1A', 'EASY'), ('NO', '-----'), ('3A', 'HARD'), ('2A', 'NORMAL')], default='NO', max_length=2, verbose_name='Зима'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('AC', 'принят'), ('RJ', 'отклонён'), ('NW', 'новый'), ('PN', 'в работе')], default='NW', max_length=2),
        ),
    ]
